// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3v24brUnKygkietBWv5EAmtDlmc9AOM',
    appId: '1:260205017836:web:573033c442b78b202f43c9',
    messagingSenderId: '260205017836',
    projectId: 'chat-fb23e',
    authDomain: 'chat-fb23e.firebaseapp.com',
    storageBucket: 'chat-fb23e.appspot.com',
    measurementId: 'G-ZBBXQD42NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGnnrVJXqQHYCYr_Wsm-wjvZWk5R53wU',
    appId: '1:260205017836:android:2739ab6e5948fd292f43c9',
    messagingSenderId: '260205017836',
    projectId: 'chat-fb23e',
    storageBucket: 'chat-fb23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2TcjomY9yKuYGAOF18PLhYnn5ZHVZzw',
    appId: '1:260205017836:ios:7644acbe9b19817c2f43c9',
    messagingSenderId: '260205017836',
    projectId: 'chat-fb23e',
    storageBucket: 'chat-fb23e.appspot.com',
    iosClientId: '260205017836-cnd0t0d44tdjve612rdojiqfvunn765p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
